# Generated by Django 2.2 on 2019-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.TextField(),
        ),
    ]
